signals:
  app:
    use: true
    NN: 8
    coreset: 1
    cleanse_scorename: "aerecon"
    percentile_cleanse: 85

  mot:
    use: true
    NN: 8
    coreset: 1
    cleanse_scorename: "velo_fgmm"
    percentile_cleanse: 85

postprocess:
  sigma: 5
